server:
  port: 80
  #http默认80，这样用户访问的时候就不用输入端口号了

spring:
  application:
    name: cloud-order-com.dsl.springcloud.service


eureka:
  client:
      #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
      #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
        defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
